
#######################################################################################
#  X Name plus no auto-start and no automatic pull requests after changes in master     #
#######################################################################################

name: $(Date:yyyyMMdd)$(Rev:.r)
trigger: none
pr: none

#######################################################################################
#             Variables                                                               #
#######################################################################################
variables:
  - group: AzureDemoGeneric

stages:
- stage: Dev_infra
  displayName: 'Dev Infra'
  variables:
  - group: Development_new
  jobs:
  - template: job-infra.yml
    parameters: {EnvironmentName: 'Development'}