
#######################################################################################
#  Name plus no auto-start and no automatic pull requests after changes in master     #
#######################################################################################

name: $(Date:yyyyMMdd)$(Rev:.r)
trigger: none
pr: none

#######################################################################################
#             Variables                                                               #
#######################################################################################
variables:
- group: 'AzureDemoGeneric'
  #####################################################################################
  # Basic settings, Must Change                                                       #
  #####################################################################################
  unique:                           'yourteamname'                         # Only lowercase letters and numbers (No uppercase or special characters)  
  ResourceGroupName:                'ft-sqlserver'                         # base name for resource group e.g. rg-dev-sqlexampleCCC-01.                                   
  location:                         'westeurope'                           # region, e.g. westeurope or northeurope.
  sqlServerName:                    'sqlserver$(unique)'                   # Unique Name of the sql server
  sqlDatabaseName:                  'sqldb$(unique)'                        # Database Name based on base name given above.
  skuTier:                          'Standard'                              # Can also be changed after deployment. Choose if you want to have a purchasing model based on Flexible configruation with vCores (Severless -> "GeneralPurpose" or Provisioned -> Hyperscale or "BusinessCritical"). Preconfigured configuration with DTU ("Basic", "Standard" or "Premium") More information check: https://docs.microsoft.com/en-us/azure/azure-sql/database/purchasing-models            
  skuName:                          'Standard'                              # Can also be changed after deployment. Only required when chosen for a Flexible configuration with vCores.
  skuCapacity:                      '10'                                    # Can also be changed after deployment. In case of Standard SKU, this would be considered as number of DTU.
  collation:                        'SQL_Latin1_General_CP1_CI_AS'          # Cannot be changed after deployment. Change this value in the YAML if your solution requires a different collation than the default value
  catalogCollation:                 'SQL_Latin1_General_CP1_CI_AS'          # Cannot be changed after deployment
  vnetName:                         'sqlvnet$(unique)'                      # Virtual Network Name
  subnetName:                       'sql'                                   # Name of subnet for sql server
  vnetCIDR:                         '10.0.0.0/16'                           # address space for the vnet
  subnetCIDR:                       '10.0.0.0/24'                           # subnet range
  storageAccountName:               'sqlsa$(unique)'                        # Vulnerability Assessment Storage Account Name.



jobs:
#####################################################################################
#             Job: Create ResourceGroup                                             #
#####################################################################################
- job: 'CreatingResourceGroup'  
  steps:

  # For dedicated subscriptions the resource group can be created any way you like. This pipeline uses Azure CLI.
  - task: AzureCLI@1
    displayName: 'Create Resource Group - Dedicated Subscription model'
    enabled: true
    name: 'create_rg_dedicated'
    inputs:
      azureSubscription: $(azureSubscription)
      scriptLocation: 'inlineScript'
      inlineScript: |
        az group create --name $(ResourceGroupName) --location $(location) --tags "ProjectName=$(unique)"

  #####################################################################################
  #             Job: Create SQL Server and backend Infrastructure                     #
  #####################################################################################
- job: 'CreatingSQLServerUsingBicep'
  dependsOn:
        - CreatingResourceGroup  
  steps:


  # Possible PowerShell task to obtain object ID from AAD group/SPN
  - task: AzureCLI@1
    displayName: 'Retrieve object ID for SPN'
    enabled: true
    name: 'Get_SPN_Object_ID'
    inputs:
      azureSubscription: $(serviceConnectionName)
      scriptLocation: 'inlineScript'
      addSpnToEnvironment: true
      inlineScript: |
        # Get the ObjectId of the Service Principal (SPN) running this script.
        # When 'addSpnToEnvironment' above is set to true, the AzureCLI task stores the appId in a bash variable misleadingly called "servicePrincipalId".
        # We need the objectId of the Service Principal instead, so we use "az ad sp show" to get it.
        spnObjectId=$(az ad app list --display-name $(spnName) --query "[0].{appId:appId}" -o tsv)
        echo $spnObjectId 
        echo "##vso[task.setvariable variable=spnObjectId]$spnObjectId"

# ####################################################################################
#             Job: Create SQLServer                                             #
# ####################################################################################

   # Deploy the example infrastructure (Azure services) using the bicep template
  - task: AzureCLI@1
    displayName: 'Deploy SQL Server Using Bicep template'
    enabled: true
    name: 'Create_SQL'
    inputs:
      azureSubscription: $(serviceConnectionName)
      scriptLocation: 'inlineScript'
      inlineScript: |

        az deployment group create \
          --name azuresqlexampledeployment \
          --resource-group $(ResourceGroupName) \
          --template-file "$(System.DefaultWorkingDirectory)/examples/template.bicep" \
          --parameters location=$(location) \
                        skuName=$(skuName) \
                        skuTier=$(skuTier) \
                        skuCapacity=$(skuCapacity) \
                        spnName=$(spnName) \
                        spnObjectId=$(spnObjectId) \
                        emailVulnerabilityReport=$(emailVulnerabilityReport) \
                        sqlServerName=$(sqlServerName) \
                        sqlDatabaseName=$(sqlDatabaseName) \
                        storageAccountName=$(storageAccountName) \
                        vnetName=$(vnetName) \
                        subnetName=$(subnetName) \
                        vnetAddressSpace=$(vnetCIDR) \
                        subnetCIDR=$(subnetCIDR) \
                        agentVirtualNetworkSubnetId=$(agentVirtualNetworkSubnetId) \
                        collation=$(collation) \
                        catalogCollation=$(catalogCollation)
